trigger: none
resources:
  repositories:
    - repository: azuredevops-templates
      type: github
      name: "yardbirdsax/azuredevopstemplates"
      ref: "refs/branches/feature/zip-and-publish-s3"
stages:
  - stage: ZipAndPublish
    displayName: Zip and Publish Sample Files
    pool:
      vmImage: ubuntu-18.04
    jobs:
      - job: ZipAndPublish
        displayName: Zip and Publish Sample Files
        steps:
          - template: zip-and-publish-s3/zip-and-publish-s3.yaml@azuredevops-templates
            parameters:
              sourcePath: zip-and-publish-s3/example/files
              archiveFileName: example.zip
              awsCredentialName: aws-account
              s3BucketName: jef-azure-devops-test
              s3BucketPath: zip-and-publish-s3/
              